//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Assets_Scripts_ResLoader_VO_AssetVOWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Assets.Scripts.ResLoader.VO.AssetVO), typeof(System.Object));
		L.RegFunction("GetInstance", GetInstance);
		L.RegFunction("New", _CreateAssets_Scripts_ResLoader_VO_AssetVO);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssets_Scripts_ResLoader_VO_AssetVO(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<UnityEngine.Object>(L, 1))
			{
				UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
				Assets.Scripts.ResLoader.VO.AssetVO obj = new Assets.Scripts.ResLoader.VO.AssetVO(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<string>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				Assets.Scripts.ResLoader.VO.AssetVO obj = new Assets.Scripts.ResLoader.VO.AssetVO(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Assets.Scripts.ResLoader.VO.AssetVO.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Assets.Scripts.ResLoader.VO.AssetVO obj = (Assets.Scripts.ResLoader.VO.AssetVO)ToLua.CheckObject<Assets.Scripts.ResLoader.VO.AssetVO>(L, 1);
			UnityEngine.Object o = obj.GetInstance();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

