//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Assets_Scripts_ResLoader_AssetLoaderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Assets.Scripts.ResLoader.AssetLoader), typeof(System.Object));
		L.RegFunction("LoadNormal", LoadNormal);
		L.RegFunction("New", _CreateAssets_Scripts_ResLoader_AssetLoader);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssets_Scripts_ResLoader_AssetLoader(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Assets.Scripts.ResLoader.AssetLoader obj = new Assets.Scripts.ResLoader.AssetLoader();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Assets.Scripts.ResLoader.AssetLoader.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadNormal(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			string arg0 = ToLua.CheckString(L, 1);
			System.Action<Assets.Scripts.ResLoader.VO.AssetVO> arg1 = (System.Action<Assets.Scripts.ResLoader.VO.AssetVO>)ToLua.CheckDelegate<System.Action<Assets.Scripts.ResLoader.VO.AssetVO>>(L, 2);
			Assets.Scripts.ResLoader.AssetLoader.LoadNormal(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

