//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Assets_Scripts_Core_Utils_DateUtilsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Assets.Scripts.Core.Utils.DateUtils), typeof(System.Object));
		L.RegFunction("GetNowSeconds", GetNowSeconds);
		L.RegFunction("GetNowSecondsStr", GetNowSecondsStr);
		L.RegFunction("GetNowYMDFormat1", GetNowYMDFormat1);
		L.RegFunction("GetNowYMDFormatALogFileName", GetNowYMDFormatALogFileName);
		L.RegFunction("GetNowYMDFormatALog", GetNowYMDFormatALog);
		L.RegFunction("GetNowYMDHMSFormat", GetNowYMDHMSFormat);
		L.RegFunction("New", _CreateAssets_Scripts_Core_Utils_DateUtils);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssets_Scripts_Core_Utils_DateUtils(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Assets.Scripts.Core.Utils.DateUtils obj = new Assets.Scripts.Core.Utils.DateUtils();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Assets.Scripts.Core.Utils.DateUtils.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNowSeconds(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			long o = Assets.Scripts.Core.Utils.DateUtils.GetNowSeconds();
			LuaDLL.tolua_pushint64(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNowSecondsStr(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = Assets.Scripts.Core.Utils.DateUtils.GetNowSecondsStr();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNowYMDFormat1(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = Assets.Scripts.Core.Utils.DateUtils.GetNowYMDFormat1();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNowYMDFormatALogFileName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = Assets.Scripts.Core.Utils.DateUtils.GetNowYMDFormatALogFileName();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNowYMDFormatALog(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = Assets.Scripts.Core.Utils.DateUtils.GetNowYMDFormatALog();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNowYMDHMSFormat(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = Assets.Scripts.Core.Utils.DateUtils.GetNowYMDHMSFormat();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

